name: Test Healthcare MCP Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        check-latest: true # Ensure only the latest compatible version is used
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install mcp and fastmcp separately to avoid dependency conflicts
        pip install mcp>=1.3.0 --no-deps
        pip install fastmcp>=0.4.1 --no-deps
        # Install other dependencies
        pip install fastapi>=0.95.0 uvicorn>=0.21.1 pydantic>=2.0.0 sqlalchemy>=2.0.0 requests>=2.28.2 pandas>=2.0.0 xmltodict>=0.13.0 beautifulsoup4>=4.12.0 python-dotenv>=1.0.0 argparse>=1.4.0 gunicorn>=20.1.0 pytest>=7.3.1 pytest-cov>=4.1.0 pytest-asyncio>=0.21.0
        
    - name: Check MCP version
      run: |
        python -c "import mcp; print(f'MCP module loaded successfully')"
        
    - name: Test server initialization
      run: |
        python -c "from src.main import mcp; print('MCP server initialization successful')"

    - name: Run tool tests (without API calls)
      run: |
        # Only run basic initialization tests without making real API calls
        python -c "
        from src.tools.clinical_trials_tool import ClinicalTrialsTool
        from src.tools.medical_terminology_tool import MedicalTerminologyTool
        
        print('Initializing Clinical Trials Tool...')
        clinical_trials_tool = ClinicalTrialsTool()
        print('Clinical Trials Tool initialized successfully')
        
        print('Initializing Medical Terminology Tool...')
        medical_terminology_tool = MedicalTerminologyTool()
        print('Medical Terminology Tool initialized successfully')
        "